### ISSUE TITLE
FileSystemException when trying to run the jar

### ISSUE THREAD

**Issue by tanguySnoeck** [Mobile-IoT-Security-Lab/ARMANDroid#2]
Hello, 

I am trying to use the jar version of your tool on [this apk](https://github.com/dineshshetty/Android-InsecureBankv2) but I get a java.nio.file.FileSystemException with the error message _The process cannot access the file because it is being used by another process_. 
Here's the stack trace :
`at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
        at sun.nio.fs.AbstractFileSystemProvider.delete(Unknown Source)
        at java.nio.file.Files.delete(Unknown Source)
        at com.sun.nio.zipfs.ZipFileSystem.sync(ZipFileSystem.java:1300)
        at com.sun.nio.zipfs.ZipFileSystem.close(ZipFileSystem.java:277)
        at util.ManifestHelper.writeAxmlhandler(ManifestHelper.java:320)
        at util.ManifestHelper.changeSdkVersion(ManifestHelper.java:78)
        at Main.main(Main.java:42)`

Regards,

**Comment by totoR13** [comment]
Hello @tanguySnoeck,

ARMANDroid is built on top of Soot, which has support for multi-dex only if the “minSdkVersion” of the app is set to 22 or higher (this is a limitation of Soot framework, as you can see in the [original comment](https://github.com/secure-software-engineering/FlowDroid/issues/61#issuecomment-412825988)).

To overcome this limitation, ARMANDroid modifies the AndroidManifest of the input application, if this is not in compliance with this requirement. Due to this work-around, when you try to protect an app with ARMANDroid, this app must not be open by other processes on your pc. 

I tried to protect your application with the following command (as explained in the [Usage section](https://github.com/Mobile-IoT-Security-Lab/ARMANDroid#-usage)) and all works as expected:
```
$ java -jar ./antirepackaging-framework-all-1.0-SNAPSHOT.jar -i ./InsecureBankv2.apk -k "${KEYSTORE_PATH}:PKCS12:${KEYSTORE_PASSWORD}:${KEYSTORE_ALIAS}" -a "${ANDROID_PATHFORMS_PATH}"
### Result Report ### 
Percentages: 
	 Percentage of Java AT: 20 %
	 Percentage of native encryption: 70 %
	 Percentage of native anti-tampering without encryption: 40 %
Total number of Java AT: 99 
Total number of QC: 13 
Detailed for types:
	Number of QC of type withNativeEncrOnly: 6
	Number of QC of type withJavaAndNativeEncr: 6
	Number of QC of type withJavaOnly: 1
	Number of QC of type withJavaAndNativeAT: 0
	Number of QC of type withNativeATOnly: 0
	Number of QC of type withoutAnyAT: 0
The max nesting level is: 1
```

Regards.
